version: "3.9"

services:
  fooderio:
    container_name: fooderio
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx_proxy
    volumes:
      - ./src:/usr/src/fooderio/src
      - ./public:/usr/src/fooderio/public
    environment:
      - YOLO=true
    restart: unless-stopped
    command: ["npm start"]

networks:
  nginx_proxy:
    external: true